"""Gateway's structural account port; implementations and ownership stay in core."""

from typing import Protocol

from flinttrade_core.account_mutation_contracts import AccountMutationRequest, AccountMutationResult


class AccountMutationProtocol(Protocol):
    """The fixed eight mutations, including all OAuth and OTP flow steps."""

    def connect(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def reconnect(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def delete(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def set_execution_default(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def rotate_credentials(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def begin_auth_flow(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def complete_auth_flow(self, request: AccountMutationRequest) -> AccountMutationResult: ...
    def adopt_legacy(self, request: AccountMutationRequest) -> AccountMutationResult: ...
