"""Pydantic models for the FlintTrade broker gateway."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class AuthFlowType(StrEnum):
    """Authentication flow required by a broker.

    Variants:
        oauth_redirect: Standard OAuth2 redirect — user is sent to broker's
            login page and returned with an authorisation code.
        totp_form: Credential form with client ID, password, and a
            time-based OTP (TOTP) generated by an authenticator app.
        api_key_direct: Static API key supplied once; no interactive login
            required per session.
        otp_sms: Single-step OTP delivered via SMS — user submits the code
            to complete authentication.
        otp_multistep: Multi-step OTP flow requiring several round-trips to
            the broker's API before a session token is obtained.  Used by
            brokers such as Samco whose 2FA involves:
            (1) request OTP → OTP sent to mobile,
            (2) submit OTP → secret key e-mailed to user,
            (3) generate access token from secret key,
            (4) login with access token + password → session token.
    """

    oauth_redirect = "oauth_redirect"
    totp_form = "totp_form"
    api_key_direct = "api_key_direct"
    otp_sms = "otp_sms"
    otp_multistep = "otp_multistep"


class AccountStatus(StrEnum):
    """Connection status of a broker account."""

    disconnected = "disconnected"
    authenticating = "authenticating"
    connected = "connected"
    error = "error"
    token_expired = "token_expired"


# ---------------------------------------------------------------------------
# Broker catalog models
# ---------------------------------------------------------------------------


class AuthMethodField(BaseModel):
    """One credential input field of a native login method.

    Args:
        name: The credential key the adapter's ``login()`` (or OAuth start)
            consumes, e.g. ``"access_token"``.
        label: Human-readable field label for the connect form.
        secret: Masked in the UI and never logged when ``True``.
        required: Whether the connect form must enforce a value.
        help: Optional inline hint rendered under the field.
    """

    name: str
    label: str
    secret: bool = False
    required: bool = True
    help: str = ""


class AuthMethod(BaseModel):
    """One login method a native broker adapter supports.

    ``kind`` tells the frontend how to drive the flow: ``"direct"`` POSTs the
    fields to the native connect route; ``"oauth"`` POSTs api_key/api_secret to
    the OAuth start route and then follows the returned ``auth_url``.

    Args:
        id: Stable method identifier (e.g. ``"access_token"``, ``"oauth"``).
        label: Human-readable method name for the method picker.
        kind: ``"direct"`` or ``"oauth"``.
        description: One-line operator guidance for the method.
        fields: The credential fields the method needs.
    """

    id: str
    label: str
    kind: str
    description: str = ""
    fields: list[AuthMethodField] = []


class MCPClientConfig(BaseModel):
    """One client configuration shape for a broker-hosted MCP server.

    The values are setup metadata only. They are never credentials, and they do
    not make FlintTrade an MCP execution proxy.
    """

    id: str
    label: str
    command: str | None = None
    args: list[str] = []
    url: str | None = None
    config: dict[str, Any] = {}


class BrokerMCPInfo(BaseModel):
    """Broker-hosted MCP server metadata.

    ``trading_supported`` describes the broker's external MCP server, not an
    in-process FlintTrade order path. Any FlintTrade-side order automation must
    still mint a safety context and dispatch through the broker router.
    """

    remote_url: str
    docs_url: str
    auth_mode: str
    reauth: str
    read_only: bool
    trading_supported: bool
    daily_reauthorization: bool = False
    login_steps: list[str] = []
    use_cases: list[str] = []
    cautions: list[str] = []
    client_configs: list[MCPClientConfig] = []


class BrokerInfo(BaseModel):
    """Static metadata describing a broker's capabilities and auth requirements.

    THE single broker catalogue record (consolidation G40): bridge metadata,
    native-adapter metadata, and the verified/coming-soon status all live here
    so no second catalogue can drift.

    Args:
        name: Canonical machine-readable broker identifier (e.g. ``"zerodha"``).
        display_name: Human-readable broker name shown in the UI.
        auth_flow: Authentication flow type the broker requires.
        exchanges: List of exchange codes the broker supports.
        max_symbols_per_ws: Maximum WebSocket subscriptions per connection.
        supports_streaming: Whether the broker offers a live WebSocket feed.
        oauth_url_template: URL template for OAuth redirect flows (``None``
            for non-OAuth flows).
        is_sandbox: Whether this entry represents a sandbox/paper environment.
        aux_params: Broker-specific auxiliary parameter names that must be
            supplied alongside the standard credentials.  The frontend uses
            this list to render the correct input fields.  For example,
            Samco's ``otp_multistep`` flow requires ``secret_api_key``,
            ``primary_ip``, and optionally ``secondary_ip``.  Values stored
            here are *field name hints only* — actual values are encrypted in
            the :class:`CredentialStore`.
        native: A native FlintTrade adapter exists for this broker (it can be
            captured through the native connect path, not only the OpenAlgo
            bridge).
        connectable: The native adapter has passed live login/read checks, so
            the UI may offer a native connect. ``native=True,
            connectable=False`` renders as "coming soon" — built but not yet
            login/read verified — and the backend refuses native connects for
            it. Promote a broker by flipping this single flag after evidence.
        auth_methods: The native login methods (empty for bridge-only brokers).
        sdk_pin: The repo-local SDK lock/package name that gates native
            activation. ``None`` means either bridge-only or native REST-only
            with no third-party SDK to attest.
        mcp: Metadata for the broker-hosted MCP server, when the broker offers
            one. This is setup/capability information, not a native-session
            credential or a FlintTrade order execution path.
    """

    name: str
    display_name: str
    auth_flow: AuthFlowType
    exchanges: list[str]
    max_symbols_per_ws: int = 3000
    supports_streaming: bool = True
    oauth_url_template: str | None = None
    is_sandbox: bool = False
    aux_params: list[str] = []
    native: bool = False
    connectable: bool = False
    auth_methods: list[AuthMethod] = []
    sdk_pin: str | None = None
    mcp: BrokerMCPInfo | None = None


class BrokerAccountInfo(BaseModel):
    """Runtime state of a single connected broker account.

    Args:
        account_id: Unique identifier for the account within the broker.
        broker: Canonical broker name matching :attr:`BrokerInfo.name`.
        label: User-facing label for this account (e.g. ``"Primary Zerodha"``).
        status: Current connection/auth status of the account.
        connected_at: UTC timestamp of the last successful connection.
        error_message: Human-readable error detail when status is ``error``.
        is_primary: Whether this is the primary account for order routing.
    """

    account_id: str
    broker: str
    label: str
    status: AccountStatus = AccountStatus.disconnected
    connected_at: datetime | None = None
    error_message: str | None = None
    is_primary: bool = False
