import { describe, expect, it } from "vitest";
import { resolveOrderFlowExchange } from "./orderFlowExchange";

describe("resolveOrderFlowExchange", () => {
  it.each([
    ["NIFTY", undefined, "NSE_INDEX"],
    ["BANKNIFTY", undefined, "NSE_INDEX"],
    ["FINNIFTY", undefined, "NSE_INDEX"],
    ["MIDCPNIFTY", undefined, "NSE_INDEX"],
    ["INDIAVIX", undefined, "NSE_INDEX"],
    ["NIFTYNXT50", undefined, "NSE_INDEX"],
    ["SENSEX", undefined, "BSE_INDEX"],
    ["BANKEX", undefined, "BSE_INDEX"],
    ["SENSEX50", undefined, "BSE_INDEX"],
    ["RELIANCE", undefined, "NSE"],
    ["NIFTY25JULFUT", undefined, "NFO"],
    ["NIFTY25JUL2525000CE", undefined, "NFO"],
    ["NIFTYNXT5025JUL26FUT", undefined, "NFO"],
    ["RELIANCE25JUL26FUT", undefined, "NFO"],
    ["SENSEX25JUL80000PE", undefined, "BFO"],
    ["SENSEX5025JUL2680000PE", undefined, "BFO"],
    ["GOLD", undefined, "MCX"],
    ["GOLD02APR26FUT", undefined, "MCX"],
    ["CRUDEOIL", undefined, "MCX"],
    ["CRUDEOIL25JANFUT", undefined, "MCX"],
    ["USDINR", undefined, "CDS"],
    ["USDINR24APR25FUT", undefined, "CDS"],
    ["USDINR24APR2583.5PE", undefined, "CDS"],
    ["EURINR", undefined, "CDS"],
    ["EURINR29JUL26FUT", undefined, "CDS"],
    ["GBPINR", undefined, "CDS"],
    ["GBPINR29JUL26120CE", undefined, "CDS"],
    ["JPYINR", undefined, "CDS"],
    ["JPYINR29JUL26FUT", undefined, "CDS"],
    ["EURUSD", undefined, "CDS"],
    ["EURUSD29JUL26FUT", undefined, "CDS"],
    ["EURUSD29JUL261.25CE", undefined, "CDS"],
    ["GBPUSD", undefined, "CDS"],
    ["GBPUSD29JUL26FUT", undefined, "CDS"],
    ["GBPUSD29JUL261.35PE", undefined, "CDS"],
    ["USDJPY", undefined, "CDS"],
    ["USDJPY29JUL26FUT", undefined, "CDS"],
    ["USDJPY29JUL26150CE", undefined, "CDS"],
    ["NIFTY", "NFO", "NFO"],
    ["NIFTY", "  nfo  ", "NFO"],
    ["RELIANCE", "  bSe  ", "BSE"],
    ["GIFTNIFTY", "NSE_INDEX", "NSE_INDEX"],
    ["MCXBULLDEX", "MCX", "MCX"],
    ["RELIANCE", "   ", "NSE"],
  ])("resolves %s on %s to %s", (symbol, explicitExchange, exchange) => {
    expect(resolveOrderFlowExchange(symbol, explicitExchange)).toBe(exchange);
  });

  it.each([
    "NIFTY100",
    "NIFTY200",
    "NIFTY500",
    "NIFTYALPHA50",
    "NIFTYAUTO",
    "NIFTYCOMMODITIES",
    "NIFTYCONSUMPTION",
    "NIFTYCPSE",
    "NIFTYDIVOPPS50",
    "NIFTYENERGY",
    "NIFTYFMCG",
    "NIFTYGROWSECT15",
    "NIFTYGS10YR",
    "NIFTYGS10YRCLN",
    "NIFTYGS1115YR",
    "NIFTYGS15YRPLUS",
    "NIFTYGS48YR",
    "NIFTYGS813YR",
    "NIFTYGSCOMPSITE",
    "NIFTYINFRA",
    "NIFTYIT",
    "NIFTYMEDIA",
    "NIFTYMETAL",
    "NIFTYMIDLIQ15",
    "NIFTYMIDCAP100",
    "NIFTYMIDCAP150",
    "NIFTYMIDCAP50",
    "NIFTYMIDSML400",
    "NIFTYMNC",
    "NIFTYPHARMA",
    "NIFTYPSE",
    "NIFTYPSUBANK",
    "NIFTYPVTBANK",
    "NIFTYREALTY",
    "NIFTYSERVSECTOR",
    "NIFTYSMLCAP100",
    "NIFTYSMLCAP250",
    "NIFTYSMLCAP50",
    "NIFTY100EQLWGT",
    "NIFTY100LIQ15",
    "NIFTY100LOWVOL30",
    "NIFTY100QUALTY30",
    "NIFTY200QUALTY30",
    "NIFTY50DIVPOINT",
    "NIFTY50EQLWGT",
    "NIFTY50PR1XINV",
    "NIFTY50PR2XLEV",
    "NIFTY50TR1XINV",
    "NIFTY50TR2XLEV",
    "NIFTY50VALUE20",
    "HANGSENGBEESNAV",
  ])("routes the canonical NSE index %s to NSE_INDEX", (symbol) => {
    expect(resolveOrderFlowExchange(symbol)).toBe("NSE_INDEX");
  });

  it.each([
    "BSE100",
    "BSE150MIDCAPINDEX",
    "BSE200",
    "BSE250LARGEMIDCAPINDEX",
    "BSE400MIDSMALLCAPINDEX",
    "BSE500",
    "BSEAUTO",
    "BSECAPITALGOODS",
    "BSECARBONEX",
    "BSECONSUMERDURABLES",
    "BSECPSE",
    "BSEDOLLEX100",
    "BSEDOLLEX200",
    "BSEDOLLEX30",
    "BSEENERGY",
    "BSEFASTMOVINGCONSUMERGOODS",
    "BSEFINANCIALSERVICES",
    "BSEGREENEX",
    "BSEHEALTHCARE",
    "BSEINDIAINFRASTRUCTUREINDEX",
    "BSEINDUSTRIALS",
    "BSEINFORMATIONTECHNOLOGY",
    "BSEIPO",
    "BSELARGECAP",
    "BSEMETAL",
    "BSEMIDCAP",
    "BSEMIDCAPSELECTINDEX",
    "BSEOIL&GAS",
    "BSEPOWER",
    "BSEPSU",
    "BSEREALTY",
    "BSESENSEXNEXT50",
    "BSESMALLCAP",
    "BSESMALLCAPSELECTINDEX",
    "BSESMEIPO",
    "BSETECK",
    "BSETELECOM",
  ])("routes the canonical BSE index %s to BSE_INDEX", (symbol) => {
    expect(resolveOrderFlowExchange(symbol)).toBe("BSE_INDEX");
  });

  it.each([
    "MCXAGRI",
    "MCXBULLDEX",
    "MCXCOMDEX",
    "MCXCOMPDEX",
    "MCXCOPRDEX",
    "MCXCRUDEX",
    "MCXENERGY",
    "MCXGOLDEX",
    "MCXMETAL",
    "MCXMETLDEX",
    "MCXSILVDEX",
  ])("routes the OpenAlgo MCX index %s to MCX_INDEX", (symbol) => {
    expect(resolveOrderFlowExchange(symbol)).toBe("MCX_INDEX");
  });

  it.each([
    "AUS200",
    "FRANCE40",
    "GERMANY40",
    "GIFTNIFTY",
    "HANGSENG",
    "JAPAN225",
    "SHANGHAICHINA",
    "UK100",
    "US100",
    "US10YRYIELD",
    "US30",
    "US500",
    "USCOMPOSITE",
  ])("routes the OpenAlgo global index %s to GLOBAL_INDEX", (symbol) => {
    expect(resolveOrderFlowExchange(symbol)).toBe("GLOBAL_INDEX");
  });

  it.each([
    ["MCXBULLDEX27MAY26FUT", "MCX"],
    ["MCXMETLDEX27MAY2615000CE", "MCX"],
    ["BSE50027MAY26FUT", "BFO"],
    ["NIFTY50027MAY2615000PE", "NFO"],
  ])("routes derivative contract %s to %s", (symbol, exchange) => {
    expect(resolveOrderFlowExchange(symbol)).toBe(exchange);
  });
});
