"""Source-pin for the production systemd install contract.

``docs/setup/linux.md`` tells operators to run ``infra/scripts/setup-production.sh``,
which copies ``infra/systemd/flinttrade.service`` into systemd. Those two files
plus ``requirements.lock`` must agree so a first-time Ubuntu host can start.

Expected contract — this module is the tracking pin. Development implements the
product fix on this same branch; do not weaken these assertions to match the
broken installer or unit.

* install prefix ``/opt/flinttrade`` (installer default matches the unit)
* installer creates a repo-local ``.venv``
* hashed lock includes gunicorn (the unit ``ExecStart``s it)
* unit sets ``FLINTTRADE_BACKEND_PORT`` (the name ``flinttrade_core.app`` reads)
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_INSTALLER = _REPO_ROOT / "infra" / "scripts" / "setup-production.sh"
_UNIT = _REPO_ROOT / "infra" / "systemd" / "flinttrade.service"
_LOCK = _REPO_ROOT / "requirements.lock"
_APP = _REPO_ROOT / "packages" / "core" / "core" / "src" / "flinttrade_core" / "app.py"

_DEFAULT_PREFIXES = (
    'INSTALL_DIR="${FLINTTRADE_DIR:-/opt/flinttrade}"',
    'INSTALL_DIR="${INSTALL_DIR:-/opt/flinttrade}"',
)
_VENV_CREATE_RE = re.compile(r"python3(?:\.\d+)? -m venv")
_GUNICORN_LOCK_RE = re.compile(r"(?m)^gunicorn==")


def _first_assignment(text: str, name: str) -> str | None:
    """Return the first ``name=…`` line in ``text``, or ``None``.

    Args:
        text: File contents to scan.
        name: Shell or unit assignment name.

    Returns:
        The matching line, or ``None`` if absent.
    """
    prefix = f"{name}="
    for line in text.splitlines():
        if line.startswith(prefix):
            return line
    return None


@pytest.mark.unit
def test_production_installer_defaults_to_systemd_prefix() -> None:
    """setup-production.sh must install where flinttrade.service already looks.

    The unit's WorkingDirectory, FLINTTRADE_HOME, EnvironmentFile, ExecStart
    and ReadWritePaths are all ``/opt/flinttrade``. A default of
    ``$HOME/FlintTrade`` leaves the copied unit pointing at a tree the
    installer never created.
    """
    installer = _INSTALLER.read_text(encoding="utf-8")
    unit = _UNIT.read_text(encoding="utf-8")
    actual = _first_assignment(installer, "INSTALL_DIR")

    assert "WorkingDirectory=/opt/flinttrade" in unit
    assert "Environment=FLINTTRADE_HOME=/opt/flinttrade" in unit
    assert "ExecStart=/opt/flinttrade/.venv/bin/gunicorn" in unit
    assert actual in _DEFAULT_PREFIXES, (
        "setup-production.sh default INSTALL_DIR must be /opt/flinttrade "
        f"(matching {_UNIT.relative_to(_REPO_ROOT).as_posix()}); got {actual!r}"
    )


@pytest.mark.unit
def test_production_installer_creates_unit_venv() -> None:
    """The installer must create the ``.venv`` the unit ExecStart's.

    Apt-installing ``python3-venv`` is not enough: the script must run
    ``python3 -m venv`` (or ``python3.x -m venv``) at the install prefix.
    Optional ``uv sync`` when uv happens to be on PATH does not satisfy this.
    """
    installer = _INSTALLER.read_text(encoding="utf-8")
    creates_venv = _VENV_CREATE_RE.search(installer) is not None
    mentions_venv_dir = ".venv" in installer

    assert creates_venv, (
        "setup-production.sh must create $INSTALL_DIR/.venv via python3 -m venv; "
        "flinttrade.service starts /opt/flinttrade/.venv/bin/gunicorn"
    )
    assert mentions_venv_dir, "setup-production.sh must name the unit venv path .venv"


@pytest.mark.unit
def test_requirements_lock_includes_gunicorn() -> None:
    """The hashed lock the installer installs must provide the unit's WSGI server.

    ``flinttrade.service`` ExecStart's ``/opt/flinttrade/.venv/bin/gunicorn``.
    ``requirements.lock`` is what ``setup-production.sh`` installs; gunicorn
    must be a locked dependency, not an implicit system package.
    """
    lock = _LOCK.read_text(encoding="utf-8")
    unit = _UNIT.read_text(encoding="utf-8")
    has_gunicorn = _GUNICORN_LOCK_RE.search(lock) is not None

    assert "ExecStart=/opt/flinttrade/.venv/bin/gunicorn" in unit
    assert has_gunicorn, (
        "requirements.lock must pin gunicorn==… "
        "(generated by uv export; add the dependency to the workspace first)"
    )


@pytest.mark.unit
def test_systemd_unit_sets_backend_port_env() -> None:
    """The unit must export the env name the backend actually reads.

    ``flinttrade_core.app._resolve_backend_port`` reads
    ``FLINTTRADE_BACKEND_PORT``. ``FLINTTRADE_PORT`` is a legacy alias only
    Docker's start helper honours. A production unit that sets the legacy
    name does not configure the backend.
    """
    unit = _UNIT.read_text(encoding="utf-8")
    app = _APP.read_text(encoding="utf-8")
    port_envs = [
        line
        for line in unit.splitlines()
        if line.startswith("Environment=FLINTTRADE_") and "PORT" in line
    ]
    sets_backend_port = any(line.startswith("Environment=FLINTTRADE_BACKEND_PORT=") for line in port_envs)

    assert 'os.environ.get("FLINTTRADE_BACKEND_PORT"' in app
    assert sets_backend_port, (
        "flinttrade.service must set Environment=FLINTTRADE_BACKEND_PORT=… "
        f"(not only the legacy FLINTTRADE_PORT name); found {port_envs}"
    )
