"""Source-pin for the production systemd install contract.

``docs/setup/linux.md`` tells operators to run ``infra/scripts/setup-production.sh``,
which copies ``infra/systemd/flinttrade.service`` into systemd. Those two files
plus ``requirements.lock`` must agree so a first-time Ubuntu host can start.

Expected contract — this module is the tracking pin. Development implements the
product fix on this same branch; do not weaken these assertions to match the
broken installer or unit.

* install prefix ``/opt/flinttrade`` (installer default matches the unit)
* installer creates a repo-local ``.venv``
* hashed lock includes gunicorn (the unit ``ExecStart``s it)
* unit sets ``FLINTTRADE_BACKEND_PORT`` (the name ``flinttrade_core.app`` reads)
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_INSTALLER = _REPO_ROOT / "infra" / "scripts" / "setup-production.sh"
_UNIT = _REPO_ROOT / "infra" / "systemd" / "flinttrade.service"
_LOCK = _REPO_ROOT / "requirements.lock"
_APP = _REPO_ROOT / "packages" / "core" / "core" / "src" / "flinttrade_core" / "app.py"

_DEFAULT_PREFIX_RE = re.compile(
    r'INSTALL_DIR="\$\{(?:FLINTTRADE_DIR|INSTALL_DIR):-/opt/flinttrade\}"'
)
_VENV_CREATE_RE = re.compile(r"python3(?:\.\d+)? -m venv")
_GUNICORN_LOCK_RE = re.compile(r"(?m)^gunicorn==")


@pytest.mark.unit
def test_production_installer_defaults_to_systemd_prefix() -> None:
    """setup-production.sh must install where flinttrade.service already looks.

    The unit's WorkingDirectory, FLINTTRADE_HOME, EnvironmentFile, ExecStart
    and ReadWritePaths are all ``/opt/flinttrade``. A default of
    ``$HOME/FlintTrade`` leaves the copied unit pointing at a tree the
    installer never created.
    """
    installer = _INSTALLER.read_text(encoding="utf-8")
    unit = _UNIT.read_text(encoding="utf-8")

    assert "WorkingDirectory=/opt/flinttrade" in unit
    assert "Environment=FLINTTRADE_HOME=/opt/flinttrade" in unit
    assert "ExecStart=/opt/flinttrade/.venv/bin/gunicorn" in unit
    assert _DEFAULT_PREFIX_RE.search(installer), (
        "setup-production.sh default INSTALL_DIR must be /opt/flinttrade "
        f"(matching {_UNIT.relative_to(_REPO_ROOT).as_posix()})"
    )


@pytest.mark.unit
def test_production_installer_creates_unit_venv() -> None:
    """The installer must create the ``.venv`` the unit ExecStart's.

    Apt-installing ``python3-venv`` is not enough: the script must run
    ``python3 -m venv`` (or ``python3.x -m venv``) at the install prefix.
    Optional ``uv sync`` when uv happens to be on PATH does not satisfy this.
    """
    installer = _INSTALLER.read_text(encoding="utf-8")

    assert _VENV_CREATE_RE.search(installer), (
        "setup-production.sh must create $INSTALL_DIR/.venv; "
        "flinttrade.service starts /opt/flinttrade/.venv/bin/gunicorn"
    )
    assert ".venv" in installer


@pytest.mark.unit
def test_requirements_lock_includes_gunicorn() -> None:
    """The hashed lock the installer installs must provide the unit's WSGI server.

    ``flinttrade.service`` ExecStart's ``/opt/flinttrade/.venv/bin/gunicorn``.
    ``requirements.lock`` is what ``setup-production.sh`` installs; gunicorn
    must be a locked dependency, not an implicit system package.
    """
    lock = _LOCK.read_text(encoding="utf-8")
    unit = _UNIT.read_text(encoding="utf-8")

    assert "ExecStart=/opt/flinttrade/.venv/bin/gunicorn" in unit
    assert _GUNICORN_LOCK_RE.search(lock), (
        "requirements.lock must pin gunicorn==… "
        "(generated by uv export; add the dependency to the workspace first)"
    )


@pytest.mark.unit
def test_systemd_unit_sets_backend_port_env() -> None:
    """The unit must export the env name the backend actually reads.

    ``flinttrade_core.app._resolve_backend_port`` reads
    ``FLINTTRADE_BACKEND_PORT``. ``FLINTTRADE_PORT`` is a legacy alias only
    Docker's start helper honours. A production unit that sets the legacy
    name does not configure the backend.
    """
    unit = _UNIT.read_text(encoding="utf-8")
    app = _APP.read_text(encoding="utf-8")

    assert 'os.environ.get("FLINTTRADE_BACKEND_PORT"' in app
    assert "Environment=FLINTTRADE_BACKEND_PORT=" in unit, (
        "flinttrade.service must set Environment=FLINTTRADE_BACKEND_PORT=… "
        "(not only the legacy FLINTTRADE_PORT name)"
    )
