#!/usr/bin/env bash
# =============================================================================
# FlintTrade — Container Entrypoint
# =============================================================================
#
# Generates .env from Docker environment variables (so secrets are never
# baked into the image), then starts the application via gunicorn.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Generate .env from environment variables
# ---------------------------------------------------------------------------
# Docker environment variables take precedence. Defaults match .env.example.
# Write to temp dir since /app may be read-only in production
ENV_FILE="${TMPDIR:-/tmp}/.env"
cat > "$ENV_FILE" << EOF
# Auto-generated by start.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit — set values via Docker environment variables.

# --- OpenAlgo connection ---
OPENALGO_HOST=${OPENALGO_HOST:-http://127.0.0.1}
OPENALGO_PORT=${OPENALGO_PORT:-5000}
OPENALGO_API_KEY=${OPENALGO_API_KEY:-}
OPENALGO_WS_PORT=${OPENALGO_WS_PORT:-8765}

# --- FlintTrade backend ---
# Canonical name is FLINTTRADE_BACKEND_PORT (what the backend reads);
# FLINTTRADE_PORT is honoured as a legacy fallback for existing deployments.
FLINTTRADE_BACKEND_PORT=${FLINTTRADE_BACKEND_PORT:-${FLINTTRADE_PORT:-5100}}
FLINTTRADE_DEV=${FLINTTRADE_DEV:-0}

# --- CORS ---
CORS_ORIGINS=${CORS_ORIGINS:-http://127.0.0.1:5173}

# --- Monitoring ---
GLITCHTIP_DSN=${GLITCHTIP_DSN:-}
EOF

# Export so python-dotenv can find the file at a writable path
export DOTENV_PATH="$ENV_FILE"
echo "[start.sh] .env generated at $ENV_FILE"

# ---------------------------------------------------------------------------
# Generate file-backed app secrets if not already present
# ---------------------------------------------------------------------------
MASTER_PASSWORD_FILE="/home/flinttrade/.flinttrade/master_password"
if [ ! -f "$MASTER_PASSWORD_FILE" ]; then
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" > "$MASTER_PASSWORD_FILE"
    chmod 600 "$MASTER_PASSWORD_FILE"
    echo "[start.sh] Master password generated at $MASTER_PASSWORD_FILE"
fi

JWT_SECRET_FILE="/home/flinttrade/.flinttrade/jwt_secret"
if [ ! -f "$JWT_SECRET_FILE" ]; then
    python3 -c "import secrets; print(secrets.token_urlsafe(48))" > "$JWT_SECRET_FILE"
    chmod 600 "$JWT_SECRET_FILE"
    echo "[start.sh] JWT secret generated at $JWT_SECRET_FILE"
fi

# ---------------------------------------------------------------------------
# Wait for OpenAlgo to be reachable (if configured)
# ---------------------------------------------------------------------------
OPENALGO_URL="${OPENALGO_HOST:-http://127.0.0.1}:${OPENALGO_PORT:-5000}"

if [ -n "${OPENALGO_API_KEY:-}" ]; then
    echo "[start.sh] Waiting for OpenAlgo at $OPENALGO_URL ..."
    retries=0
    max_retries=30
    until curl -sf "$OPENALGO_URL/api/v1/ping" > /dev/null 2>&1; do
        retries=$((retries + 1))
        if [ "$retries" -ge "$max_retries" ]; then
            echo "[start.sh] WARNING: OpenAlgo not reachable after ${max_retries} attempts. Starting anyway."
            break
        fi
        sleep 2
    done
    if [ "$retries" -lt "$max_retries" ]; then
        echo "[start.sh] OpenAlgo is reachable."
    fi
fi

# ---------------------------------------------------------------------------
# Start gunicorn
# ---------------------------------------------------------------------------
BACKEND_PORT="${FLINTTRADE_BACKEND_PORT:-${FLINTTRADE_PORT:-5100}}"
echo "[start.sh] Starting FlintTrade on port ${BACKEND_PORT} ..."

exec gunicorn \
    --worker-class eventlet \
    -w "${GUNICORN_WORKERS:-1}" \
    --bind "0.0.0.0:${BACKEND_PORT}" \
    --timeout "${GUNICORN_TIMEOUT:-120}" \
    --graceful-timeout 30 \
    --keep-alive 5 \
    --access-logfile - \
    --error-logfile - \
    --log-level "${LOG_LEVEL:-info}" \
    'flinttrade_core.app:app'
