"""QuantStats tearsheet generation for FlintTrade backtest results.

Wraps the QuantStats library (optional dependency) to produce HTML tearsheets,
compact snapshots, and multi-strategy comparison reports. All functions degrade
gracefully when QuantStats is not installed, returning an informative HTML
stub instead of raising an exception.

References:
    - marketcalls/VectorBT-Tearsheets (vectorbt + quantstats integration)
    - quantstats.readthedocs.io

Usage::

    from packages.backtest_engine.src.tearsheet import (
        generate_tearsheet,
        generate_snapshot,
        compare_strategies,
        save_tearsheet,
    )

    html = generate_tearsheet(returns, benchmark_returns=nifty_returns, title="EMA Strategy")
    save_tearsheet(html, "/tmp/ema_strategy.html")
"""

from __future__ import annotations

import io
import logging
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd

logger = logging.getLogger("flinttrade.backtest.tearsheet")

# ---------------------------------------------------------------------------
# Optional import — quantstats
# ---------------------------------------------------------------------------

try:
    import quantstats as qs  # type: ignore[import-untyped]

    _QS_AVAILABLE = True
    qs.extend_pandas()  # Adds .sharpe(), .sortino(), etc. to pd.Series
except ImportError:
    qs = None  # type: ignore[assignment]  # Kept as a patchable name for tests.
    _QS_AVAILABLE = False
    logger.debug(
        "quantstats not installed. Tearsheet generation will return stub HTML. "
        "Install with: pip install quantstats"
    )


# ---------------------------------------------------------------------------
# Branding helpers
# ---------------------------------------------------------------------------

_BRAND_CSS = textwrap.dedent("""\
    <style>
      .ft-header {
        background: #0a0a0f;
        color: #e8e8f0;
        padding: 18px 32px;
        font-family: 'Geist', 'Inter', system-ui, sans-serif;
        display: flex;
        align-items: center;
        gap: 16px;
        border-bottom: 1px solid #2a2a3a;
      }
      .ft-header .ft-logo {
        font-size: 1.4rem;
        font-weight: 700;
        letter-spacing: -0.5px;
        color: #c8c8e8;
      }
      .ft-header .ft-title {
        font-size: 1.1rem;
        color: #9090b0;
        margin-left: auto;
      }
      .ft-footer {
        background: #0a0a0f;
        color: #505068;
        text-align: center;
        padding: 12px;
        font-family: 'Inter', system-ui, sans-serif;
        font-size: 0.75rem;
        border-top: 1px solid #2a2a3a;
        margin-top: 24px;
      }
    </style>
""")

_BRAND_HEADER_TEMPLATE = textwrap.dedent("""\
    <div class="ft-header">
      <span class="ft-logo">FlintTrade</span>
      <span class="ft-title">{title}</span>
    </div>
""")

_BRAND_FOOTER = textwrap.dedent("""\
    <div class="ft-footer">
      Generated by FlintTrade Backtest Engine &mdash; for informational purposes only.
      Past performance does not guarantee future results.
    </div>
""")

_STUB_TEMPLATE = textwrap.dedent("""\
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>FlintTrade — {title}</title>
      {css}
    </head>
    <body style="background:#0a0a0f;color:#e8e8f0;font-family:'Inter',system-ui,sans-serif;padding:32px;">
      {header}
      <div style="margin:40px auto;max-width:600px;text-align:center;padding:48px;
                  background:#16161f;border-radius:12px;border:1px solid #2a2a3a;">
        <h2 style="color:#9090b0;">Tearsheet Unavailable</h2>
        <p style="color:#707090;">{message}</p>
        <code style="background:#0a0a0f;padding:8px 16px;border-radius:6px;
                     color:#c8c8e8;font-size:0.85rem;">pip install quantstats</code>
      </div>
      {footer}
    </body>
    </html>
""")


def _brand_html(inner_html: str, title: str) -> str:
    """Inject FlintTrade branding into an existing HTML string.

    Prepends the branded header and appends the footer. Handles both full
    ``<!DOCTYPE html>`` documents from QuantStats and bare HTML fragments.

    Args:
        inner_html: Raw HTML from QuantStats or another source.
        title: Strategy or report title shown in the header bar.

    Returns:
        Branded HTML string.
    """
    header = _BRAND_HEADER_TEMPLATE.format(title=title)
    injection = _BRAND_CSS + "\n" + header

    # Insert after <body> if present; prepend otherwise.
    if "<body" in inner_html:
        insert_after = inner_html.find(">", inner_html.find("<body")) + 1
        branded = (
            inner_html[:insert_after]
            + "\n"
            + injection
            + inner_html[insert_after:]
        )
    else:
        branded = injection + inner_html

    # Append footer before </body> if present; otherwise append.
    if "</body>" in branded:
        branded = branded.replace("</body>", _BRAND_FOOTER + "\n</body>")
    else:
        branded += "\n" + _BRAND_FOOTER

    return branded


def _stub_html(title: str, message: str) -> str:
    """Return a minimal branded stub page when QuantStats is unavailable.

    Args:
        title: Report title.
        message: Human-readable reason the tearsheet could not be generated.

    Returns:
        Self-contained HTML string.
    """
    return _STUB_TEMPLATE.format(
        title=title,
        css=_BRAND_CSS,
        header=_BRAND_HEADER_TEMPLATE.format(title=title),
        message=message,
        footer=_BRAND_FOOTER,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_tearsheet(
    returns: "pd.Series",
    benchmark_returns: "pd.Series | None" = None,
    title: str = "Strategy",
) -> str:
    """Generate a full QuantStats HTML tearsheet with FlintTrade branding.

    Produces a self-contained HTML document containing:
    - Equity curve and drawdown charts
    - Monthly returns heatmap
    - Rolling Sharpe and Sortino
    - 30+ performance and risk metrics

    Args:
        returns: Daily returns as a ``pandas.Series`` with a ``DatetimeIndex``.
            Values should be fractional (0.01 = 1%), not percentage.
        benchmark_returns: Optional benchmark returns Series (e.g. Nifty 50).
            When provided, all metrics are shown relative to the benchmark.
        title: Report title shown in the header bar and HTML ``<title>``.

    Returns:
        Self-contained HTML string. Returns a stub page if QuantStats is not
        installed or if an error occurs during generation.
    """
    if not _QS_AVAILABLE:
        return _stub_html(
            title=title,
            message="quantstats is not installed. Install it to generate tearsheets.",
        )

    try:
        buf = io.StringIO()
        qs.reports.html(
            returns,
            benchmark=benchmark_returns,
            title=title,
            output=buf,
        )
        raw_html = buf.getvalue()
        return _brand_html(raw_html, title=title)
    except Exception as exc:
        logger.error("generate_tearsheet failed for '%s': %s", title, exc)
        return _stub_html(title=title, message=f"Tearsheet generation failed: {exc}")


def generate_snapshot(
    returns: "pd.Series",
    title: str = "Strategy",
) -> str:
    """Generate a compact snapshot report as an HTML page.

    The snapshot renders a single combined figure (equity curve + Sharpe +
    monthly distribution) — smaller and faster than the full tearsheet.

    Args:
        returns: Daily returns ``pandas.Series``.
        title: Chart title.

    Returns:
        HTML string containing the embedded snapshot image, or a stub page.
    """
    if not _QS_AVAILABLE:
        return _stub_html(
            title=title,
            message="quantstats is not installed. Install it to generate snapshots.",
        )

    try:
        import base64

        import matplotlib
        matplotlib.use("Agg")  # Non-interactive backend — safe in server contexts.
        import matplotlib.pyplot as plt

        fig = qs.plots.snapshot(returns, title=title, show=False)
        if fig is None:
            # QuantStats may return None depending on version; fall back.
            fig = plt.gcf()

        img_buf = io.BytesIO()
        fig.savefig(img_buf, format="png", dpi=120, bbox_inches="tight", facecolor="#0a0a0f")
        plt.close(fig)

        img_b64 = base64.b64encode(img_buf.getvalue()).decode("ascii")
        img_tag = (
            f'<img src="data:image/png;base64,{img_b64}" '
            f'style="max-width:100%;border-radius:8px;" alt="{title} snapshot">'
        )

        inner = textwrap.dedent(f"""\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>FlintTrade — {title} Snapshot</title>
            </head>
            <body style="background:#0a0a0f;padding:0;margin:0;">
              {img_tag}
            </body>
            </html>
        """)
        return _brand_html(inner, title=f"{title} — Snapshot")
    except Exception as exc:
        logger.error("generate_snapshot failed for '%s': %s", title, exc)
        return _stub_html(title=title, message=f"Snapshot generation failed: {exc}")


def compare_strategies(
    strategy_returns: dict[str, "pd.Series"],
) -> str:
    """Generate a multi-strategy comparison report as an HTML page.

    Overlays equity curves for all strategies on a single chart and renders
    a side-by-side metrics table (Sharpe, Sortino, CAGR, Max Drawdown, etc.).

    Args:
        strategy_returns: Mapping of strategy name to daily returns ``Series``.
            All series should share the same date range for meaningful comparison.

    Returns:
        Self-contained HTML string, or a stub page on failure.

    Example::

        html = compare_strategies({
            "EMA Cross": ema_returns,
            "RSI Mean Reversion": rsi_returns,
            "Buy & Hold": nifty_returns,
        })
        save_tearsheet(html, "/tmp/comparison.html")
    """
    if not _QS_AVAILABLE:
        return _stub_html(
            title="Strategy Comparison",
            message="quantstats is not installed. Install it to compare strategies.",
        )

    if not strategy_returns:
        return _stub_html(title="Strategy Comparison", message="No strategies provided.")

    try:
        import base64

        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import pandas as pd

        # ---- Equity curves overlay ----------------------------------------
        fig, ax = plt.subplots(figsize=(14, 5), facecolor="#0a0a0f")
        ax.set_facecolor("#16161f")
        ax.tick_params(colors="#9090b0")
        for spine in ax.spines.values():
            spine.set_edgecolor("#2a2a3a")

        colours = [
            "#7c6aff", "#22d3ee", "#f59e0b", "#34d399",
            "#f87171", "#a78bfa", "#fb923c", "#60a5fa",
        ]

        for idx, (name, ret) in enumerate(strategy_returns.items()):
            cum = (1 + ret).cumprod()
            ax.plot(
                cum.index,
                cum.values,
                label=name,
                color=colours[idx % len(colours)],
                linewidth=1.8,
            )

        ax.legend(
            facecolor="#16161f",
            edgecolor="#2a2a3a",
            labelcolor="#c8c8e8",
            fontsize=9,
        )
        ax.set_title("Equity Curves", color="#c8c8e8", fontsize=11)
        ax.set_xlabel("Date", color="#9090b0", fontsize=9)
        ax.set_ylabel("Growth of ₹1", color="#9090b0", fontsize=9)
        plt.tight_layout()

        chart_buf = io.BytesIO()
        fig.savefig(chart_buf, format="png", dpi=120, bbox_inches="tight", facecolor="#0a0a0f")
        plt.close(fig)
        chart_b64 = base64.b64encode(chart_buf.getvalue()).decode("ascii")
        chart_html = (
            f'<img src="data:image/png;base64,{chart_b64}" '
            f'style="max-width:100%;border-radius:8px;" alt="Equity Curves">'
        )

        # ---- Metrics table ------------------------------------------------
        rows: list[dict[str, object]] = []
        for name, ret in strategy_returns.items():
            try:
                total_return = float((1 + ret).prod() - 1) * 100
                ann_ret = float(qs.stats.cagr(ret)) * 100
                sharpe = float(qs.stats.sharpe(ret))
                sortino = float(qs.stats.sortino(ret))
                max_dd = float(qs.stats.max_drawdown(ret)) * 100
                vol = float(qs.stats.volatility(ret)) * 100
                calmar = float(qs.stats.calmar(ret))
                win_rate = float(qs.stats.win_rate(ret)) * 100
            except Exception:
                total_return = ann_ret = sharpe = sortino = 0.0
                max_dd = vol = calmar = win_rate = 0.0

            rows.append({
                "Strategy": name,
                "Total Return (%)": f"{total_return:.1f}",
                "CAGR (%)": f"{ann_ret:.1f}",
                "Sharpe": f"{sharpe:.2f}",
                "Sortino": f"{sortino:.2f}",
                "Max Drawdown (%)": f"{max_dd:.1f}",
                "Volatility (%)": f"{vol:.1f}",
                "Calmar": f"{calmar:.2f}",
                "Win Rate (%)": f"{win_rate:.1f}",
            })

        df = pd.DataFrame(rows).set_index("Strategy")
        table_html = df.to_html(
            classes="ft-metrics-table",
            border=0,
            justify="center",
        )

        table_css = textwrap.dedent("""\
            <style>
              .ft-metrics-table {
                border-collapse: collapse;
                width: 100%;
                font-family: 'JetBrains Mono', 'Fira Mono', monospace;
                font-size: 0.85rem;
                color: #c8c8e8;
              }
              .ft-metrics-table th {
                background: #16161f;
                color: #9090b0;
                padding: 8px 14px;
                border-bottom: 1px solid #2a2a3a;
                text-align: center;
              }
              .ft-metrics-table td {
                background: #0d0d16;
                padding: 7px 14px;
                border-bottom: 1px solid #1e1e2e;
                text-align: center;
              }
              .ft-metrics-table tr:hover td { background: #16161f; }
            </style>
        """)

        inner = textwrap.dedent(f"""\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>FlintTrade — Strategy Comparison</title>
            </head>
            <body style="background:#0a0a0f;color:#e8e8f0;
                         font-family:'Inter',system-ui,sans-serif;padding:0;margin:0;">
              <div style="padding:24px 32px;">
                {chart_html}
                <div style="margin-top:32px;">
                  <h3 style="color:#9090b0;font-weight:500;margin-bottom:12px;">
                    Performance Metrics
                  </h3>
                  {table_css}
                  {table_html}
                </div>
              </div>
            </body>
            </html>
        """)
        return _brand_html(inner, title="Strategy Comparison")

    except Exception as exc:
        logger.error("compare_strategies failed: %s", exc)
        return _stub_html(
            title="Strategy Comparison",
            message=f"Comparison generation failed: {exc}",
        )


def save_tearsheet(html: str, filepath: str | Path) -> None:
    """Write a tearsheet HTML string to a file.

    Creates parent directories if they do not already exist. Overwrites any
    existing file at the given path.

    Args:
        html: HTML string returned by :func:`generate_tearsheet`,
            :func:`generate_snapshot`, or :func:`compare_strategies`.
        filepath: Destination path. May be a string or :class:`~pathlib.Path`.
            Parent directories are created automatically.

    Raises:
        OSError: If the file cannot be written (permissions, disk full, etc.).
    """
    dest = Path(filepath)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html, encoding="utf-8")
    logger.info("Tearsheet saved to %s", dest)
