// AUTO-GENERATED by scripts/regenerate-csp-style-hashes.ts — do not edit by hand.
//
// sha256 hashes of the small set of inline style="..." strings radix-floating-ui emits
// for runtime-computed positions. They let style-src forbid 'unsafe-inline' while still
// permitting the load-bearing radix positions (§9.4.5). Regenerate only on a radix-ui
// version bump; the result is deterministic and committed.
export const INLINE_STYLE_HASHES = [
  "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='", // empty-string placeholder; replace per §9.4.5
] as const;
