// Regenerate src/lib/csp-style-hashes.generated.ts (§9.4.5).
//
// radix-floating-ui's positioning rules emit style="position:absolute; top:…; left:…;
// transform:…" attributes that cannot be expressed as classes (runtime-computed values),
// so they need explicit sha256 hashes in style-src. Run this only when radix-ui bumps;
// the generated file is committed and is the source of truth for the CSP.
//
// Usage (site must be running on :3000):
//   pnpm --dir packages/apps/site exec tsx scripts/regenerate-csp-style-hashes.ts

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

import { chromium } from "playwright";

const ROUTES_TO_PROBE = [
  "http://127.0.0.1:3000/",
  "http://127.0.0.1:3000/docs",
  "http://127.0.0.1:3000/playground/dialog",
  "http://127.0.0.1:3000/playground/dropdown-menu",
  "http://127.0.0.1:3000/playground/popover",
  "http://127.0.0.1:3000/playground/tooltip",
  "http://127.0.0.1:3000/playground/select",
];

async function main(): Promise<void> {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const seenHashes = new Set<string>();

  for (const url of ROUTES_TO_PROBE) {
    try {
      await page.goto(url, { waitUntil: "networkidle" });
    } catch {
      continue; // a route may not exist yet; skip it
    }
    // Trigger every radix overlay so its inline styles appear.
    await page.evaluate(() => {
      document
        .querySelectorAll<HTMLElement>("[data-radix-trigger]")
        .forEach((el) => el.click());
    });
    await page.waitForTimeout(500);
    const inlineStyles = await page.$$eval("[style]", (els) =>
      els.map((el) => el.getAttribute("style") ?? ""),
    );
    for (const style of inlineStyles) {
      if (!style) continue;
      const hash = createHash("sha256").update(style).digest("base64");
      seenHashes.add(`'sha256-${hash}='`);
    }
  }

  const hashes = Array.from(seenHashes).sort();
  // Keep the empty-string placeholder so style-src is never empty on a fresh probe.
  if (hashes.length === 0) {
    hashes.push("'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='");
  }
  const output =
    "// AUTO-GENERATED by scripts/regenerate-csp-style-hashes.ts — do not edit by hand.\n" +
    "export const INLINE_STYLE_HASHES = [\n" +
    hashes.map((h) => `  ${JSON.stringify(h)},`).join("\n") +
    "\n] as const;\n";

  writeFileSync("src/lib/csp-style-hashes.generated.ts", output);
  await browser.close();
  // eslint-disable-next-line no-console
  console.log(`wrote ${hashes.length} inline-style hashes`);
}

main();
