"""Master-password input tests (SC-01; locked decision #13).

The master password must come ONLY from the hardened at-rest file, a pipe FD,
or a TTY getpass prompt — NEVER the MASTER_PASSWORD environment variable and
NEVER an auto-generated default.
"""

from __future__ import annotations

import os

import pytest

import flinttrade_core.app as app_mod


@pytest.fixture
def reset_cache():
    saved = app_mod._MASTER_PASSWORD
    app_mod._MASTER_PASSWORD = None
    yield
    app_mod._MASTER_PASSWORD = saved


def _clear_pw_env(monkeypatch) -> None:
    monkeypatch.delenv("MASTER_PASSWORD", raising=False)
    monkeypatch.delenv("FLINTTRADE_MASTER_PASSWORD_FD", raising=False)


def test_reads_from_hardened_file_ignores_env(tmp_path, monkeypatch, reset_cache) -> None:
    monkeypatch.setenv("FLINTTRADE_WORKSPACE_DIR", str(tmp_path))
    monkeypatch.setenv("MASTER_PASSWORD", "EVIL-FROM-ENV")  # must be IGNORED
    monkeypatch.delenv("FLINTTRADE_MASTER_PASSWORD_FD", raising=False)
    (tmp_path / "master_password").write_text("GOOD-FROM-FILE")
    assert app_mod._get_master_password() == "GOOD-FROM-FILE"


def test_env_var_alone_is_ignored_and_raises(tmp_path, monkeypatch, reset_cache) -> None:
    """No file, no fd, no TTY → must RAISE, never silently fall back to env."""
    monkeypatch.setenv("FLINTTRADE_WORKSPACE_DIR", str(tmp_path))  # empty: no file
    monkeypatch.setenv("MASTER_PASSWORD", "EVIL-FROM-ENV")
    monkeypatch.delenv("FLINTTRADE_MASTER_PASSWORD_FD", raising=False)
    with pytest.raises(RuntimeError):
        app_mod._get_master_password()


def test_reads_from_fd(tmp_path, monkeypatch, reset_cache) -> None:
    monkeypatch.setenv("FLINTTRADE_WORKSPACE_DIR", str(tmp_path))
    _clear_pw_env(monkeypatch)
    r, w = os.pipe()
    os.write(w, b"PW-FROM-FD\n")
    os.close(w)
    monkeypatch.setenv("FLINTTRADE_MASTER_PASSWORD_FD", str(r))
    assert app_mod._get_master_password() == "PW-FROM-FD"


def test_no_autogenerated_default(tmp_path, monkeypatch, reset_cache) -> None:
    """A fresh workspace must NOT silently mint a random master password."""
    monkeypatch.setenv("FLINTTRADE_WORKSPACE_DIR", str(tmp_path))
    _clear_pw_env(monkeypatch)
    with pytest.raises(RuntimeError):
        app_mod._get_master_password()
    # nothing was persisted either
    assert not (tmp_path / "master_password").exists()
